CREATE DATABASE AmazingBookDB;
GO
Use AmazingBookDB;

CREATE TABLE Users(
Id INT PRIMARY KEY IDENTITY(1,1),
LoginId VARCHAR(50),
Password BINARY(32),
Name VARCHAR(100),
Email VARCHAR (100) NOT NULL,
Phone VARCHAR(15) NOT NULL,
Role VARCHAR(30) DEFAULT 'Customer',
IsActive BIT DEFAULT 'Y'
);


CREATE TABLE Address(
Id INT PRIMARY KEY IDENTITY(1,1),
AddressLine1 VARCHAR(60) NOT NULL, 
AddressLine2 VARCHAR(50), 
City VARCHAR(50) NOT NULL, 
State VARCHAR(2) NOT NULL, 
Country VARCHAR(30) NOT NULL, 
Zip VARCHAR(15) NOT NULL, 
Type VARCHAR(20) NOT NULL, 
FKUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
IsActive BIT DEFAULT 'Y'
);


CREATE TABLE Book(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(200) NOT NULL,
Author VARCHAR(100) NOT NULL,
Price DECIMAL(6,2) NOT NULL,
PublicationDate DATETIME,
ImgUrl VARCHAR(250),
Description VARCHAR(800),
Language VARCHAR(50),
Isbn VARCHAR(13),
Pages INT,
Hardcover BIT,
Weight DECIMAL(5,2),
Quantity INT,
Genre VARCHAR(50)
);

CREATE TABLE Cart(
Id INT PRIMARY KEY IDENTITY(1,1),
FKUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
FKBookId INT FOREIGN KEY REFERENCES Book(Id) NOT NULL,
Quantity INT,
);

CREATE TABLE Orders(
Id INT PRIMARY KEY IDENTITY(1,1),
OrderDate DATETIME NOT NULL,
SubTotal DECIMAL(6,2) NOT NULL,
Tax DECIMAL(6,2),
Shipping DECIMAL(6,2),
Total DECIMAL(6,2) NOT NULL,
Status VARCHAR(50) NOT NULL,
CancellationDate DATETIME,
Weight DECIMAL(6,2) NOT NULL,
FKShippingAddress INT FOREIGN KEY REFERENCES Address(Id) NOT NULL,
FKUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
);

CREATE TABLE OrderLine(
Id INT PRIMARY KEY IDENTITY(1,1),
Amount DECIMAL(6,2) NOT NULL,
Quantity INT NOT NULL,
Weight DECIMAL(5,2),
FKOrderId INT FOREIGN KEY REFERENCES Orders(Id) NOT NULL,
FKBookId INT FOREIGN KEY REFERENCES Book(Id) NOT NULL
);

ALTER TABLE address
ADD name VARCHAR(200);

Alter Table Address
Drop Column Type

ALTER TABLE address
ADD IsDefault BIT DEFAULT 0 NOT NULL; 


ALTER TABLE Orders
ADD PaymentMethod VARCHAR(20),
 PaymentStatus VARCHAR(20);
 
CREATE TABLE Request 
(
 Id INT PRIMARY KEY IDENTITY(1,1),
 FkUser INT FOREIGN KEY REFERENCES Users(id) NOT NULL,
 SelfLink VARCHAR(300),
 Title VARCHAR(200) NOT NULL,
 Author VARCHAR(100) NOT NULL,
 Status VARCHAR(2) NOT NULL
)

ALTER TABLE book
ALTER COLUMN ImgUrl VARCHAR(350)
